version: "3"
services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
  elearning-api:
    # image: directus/directus:10.9.0
    # image: directus/directus:10.8.3
    build: ./
    ports:
      - 8066:8066
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./.env:/directus/.env
    environment:
      KEY: "directus-key"
      SECRET: "directus-secret"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "1"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
      EMAIL_VERIFY_SETUP: true
      EMAIL_TRANSPORT: "smtp"
      EMAIL_SMTP_HOST: "mailhog"
      EMAIL_SMTP_PORT: 1025
      CORS_ENABLED: true
      CORS_ORIGIN: true
      EXTENSIONS_AUTO_RELOAD: true
      ACCESS_TOKEN_TTL: "30d"
      REFRESH_TOKEN_TTL: "60d"
